apps/trade/urls.py
# -*- encoding: utf-8 -*-

from django.urls import path

from .views import *

urlpatterns = [
    path('masters/', masters, name="masters"),
    path('orders/', orders, name="orders"),
]

core/urls.py
# -*- encoding: utf-8 -*-

from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

admin.site.site_header = _("Trader")
admin.site.site_title = _("Trader")
admin.site.index_title = _('Welcome to Administration Panel')

urlpatterns = [
    path('admin/', admin.site.urls),        # Django admin route
    path("", include("apps.trade.urls")),
    path("", include("apps.myauth.urls")),    # Auth routes - login / register
    path("", include("apps.home.urls")),     # UI Kits Html files
]

apps/trade/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.myauth.models import User


class Trader(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='trader')
    is_master = models.BooleanField(default=False)
    kc_key = models.CharField(max_length=24, unique=True)
    kc_secret = models.CharField(max_length=36)
    kc_passphrase = models.CharField(max_length=32)
    kc_last_sync = models.DateTimeField(null=True, blank=True)

    kc_spot_access = models.BooleanField(default=False)
    kc_margin_access = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('trader')
        verbose_name_plural = _('traders')

    def __str__(self):
        return self.user.username


class Follow(models.Model):
    master = models.ForeignKey(Trader, on_delete=models.CASCADE, related_name='followers')
    slave = models.ForeignKey(Trader, on_delete=models.CASCADE, related_name='followings')
    max_loss = models.FloatField(blank=True, null=True)
    max_trading_rate = models.FloatField(blank=True, null=True)

    class Meta:
        verbose_name = _('following')
        verbose_name_plural = _('followings')
        constraints = (
            models.UniqueConstraint(fields=('master', 'slave'),
                                    name='trade_follow_master_slave_uniq'),
        )

    def __str__(self):
        return "%s → %s" % (self.slave, self.master)


class FollowSymbol(models.Model):
    follow = models.ForeignKey(Follow, on_delete=models.CASCADE, related_name='symbols')
    symbol = models.CharField(max_length=127)


class Account(models.Model):
    trader = models.ForeignKey(Trader, on_delete=models.CASCADE, related_name='accounts')
    kc_id = models.CharField(max_length=24, unique=True)
    currency = models.CharField(max_length=63)
    type = models.CharField(max_length=63)
    balance = models.FloatField(default=.0)
    available = models.FloatField(default=.0)
    holds = models.FloatField(default=.0)

    class Meta:
        verbose_name = _('account')
        verbose_name_plural = _('accounts')

    def __str__(self):
        return "%s %s" % (self.trader, self.currency)


class Order(models.Model):
    class Status(models.TextChoices):
        ACTIVE = 'ACTIVE', _('active')
        DONE = 'DONE', _('done')
        CANCELLED = 'CANCELLED', _('cancelled')

    class Side(models.TextChoices):
        SELL = 'sell', _('sell')
        BUY = 'buy', _('buy')

    trader = models.ForeignKey(Trader, on_delete=models.CASCADE, related_name='orders')
    origin = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='copies', blank=True, null=True)
    status = models.CharField(max_length=63, choices=Status.choices, default=Status.ACTIVE)
    kc_id = models.CharField(max_length=24, unique=True)
    kc_created_at = models.DateTimeField()
    src_currency = models.CharField(max_length=63)
    dst_currency = models.CharField(max_length=63)
    price = models.FloatField()
    side = models.CharField(max_length=15, choices=Side.choices)
    size = models.FloatField()
    src_usd = models.FloatField()
    dst_usd = models.FloatField()

    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')

    def __str__(self):
        return "%s %s-%s" % (self.trader, self.src_currency, self.dst_currency)

apps/trade/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.csrf import csrf_exempt

from apps.trade.models import Trader, Follow, FollowSymbol


@csrf_exempt
@login_required(login_url="/login/")
def masters(request):
    context = {
        'segment': 'masters',
        'masters': Trader.objects.filter(is_master=True).annotate(
            is_followed=Exists(Follow.objects.filter(master=OuterRef('pk'), slave=request.user.trader))),
        'is_master': hasattr(request.user, 'trader') and request.user.trader.is_master,
    }

    if request.method == 'POST':
        action = request.POST.dict()['action']
        master_id = request.POST.dict()['master_id']
        master = Trader.objects.get(id=master_id, is_master=True)
        if action == 'follow':
            if not Follow.objects.filter(master=master, slave=request.user.trader).exists():
                follow = Follow()
                follow.master = master
                follow.slave = request.user.trader
                if request.POST.dict()['max_loss']:
                    follow.max_loss = request.POST.dict()['max_loss']
                if request.POST.dict()['max_trading_rate']:
                    follow.max_trading_rate = request.POST.dict()['max_trading_rate']
                follow.save()
                if request.POST.dict()['symbols']:
                    for symbol in request.POST.dict()['symbols'].split(','):
                        FollowSymbol.objects.create(follow=follow, symbol=symbol.strip())
        elif action == 'unfollow':
            Follow.objects.filter(master=master, slave=request.user.trader).delete()

    html_template = loader.get_template('trade/masters.html')
    return HttpResponse(html_template.render(context, request))


@login_required(login_url="/login/")
def orders(request):
    orders = {}
    if hasattr(request.user, 'trader'):
        for order in request.user.trader.orders.all():
            orders[order.status] = orders.get(order.status, []) + [order]

    context = {
        'segment': 'orders',
        'orders': orders,
    }

    html_template = loader.get_template('trade/orders.html')
    return HttpResponse(html_template.render(context, request))

apps/templates/trade/masters.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Top Traders</h4>
                    <p class="card-category"> Here is a list of top traders you can follow</p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class=" text-primary">
                            <th>
                                ID
                            </th>
                            <th>
                                Name
                            </th>
                            <th></th>
                            </thead>
                            <tbody>
                            {% for master in masters %}
                                <tr>
                                    <td>
                                        {{ master.id }}
                                    </td>
                                    <td>
                                        {{ master.user.username }}
                                    </td>
                                    <td>
                                        {% if not is_master %}
                                            {% if not master.is_followed %}
                                                <form class="d-flex align-items-center justify-content-end" method="POST">
                                                    <input name="symbols" type="text" class="form-control" placeholder="ETH-BTC, ETH-USDT, ..." />
                                                    <input name="max_loss" type="number" class="form-control" placeholder="Max Loss" step="0.0001" min="0" />
                                                    <input name="max_trading_rate" type="number" class="form-control" placeholder="Max Trading Rate" step="1" min="0" max="100" />
                                                    <input type="hidden" name="master_id" value="{{ master.id }}"/>
                                                    <input type="hidden" name="action" value="follow" />
                                                    <button type="submit" class="btn btn-primary">
                                                        Follow
                                                    </button>
                                                </form>
                                            {% else %}
                                                <form method="POST">
                                                    <input type="hidden" name="master_id" value="{{ master.id }}"/>
                                                    <input type="hidden" name="action" value="unfollow" />
                                                    <button type="submit" class="btn btn-primary">
                                                        Unfollow
                                                    </button>
                                                </form>
                                            {% endif %}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/trade/orders.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header card-header-tabs card-header-primary">
                    <div class="nav-tabs-navigation">
                        <div class="nav-tabs-wrapper">
                            <span class="nav-tabs-title">Orders:</span>
                            <ul class="nav nav-tabs" data-tabs="tabs">
                                {% for status in orders %}
                                    <li class="nav-item">
                                        <a class="nav-link {% if forloop.counter == 1 %}active{% endif %}"
                                           href="#{{ status }}" data-toggle="tab">
                                            {{ status }}
                                            <div class="ripple-container"></div>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        {% for status, order_set in orders.items %}
                            <div class="tab-pane {% if forloop.counter == 1 %}active{% endif %}" id="{{ status }}">
                                <table class="table">
                                    <thead>
                                    <th>Source currency</th>
                                    <th>Dest currency</th>
                                    <th>price</th>
                                    <th>size</th>
                                    </thead>
                                    <tbody>
                                    {% for order in order_set %}
                                        <tr>
                                            <td>{{ order.src_currency }}</td>
                                            <td>{{ order.dst_currency }}</td>
                                            <td>{{ order.price }}</td>
                                            <td>{{ order.size }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}